### PR TITLE
added background image to About Us, Alumni now collapsable, made icon…

### PR DESCRIPTION
**Pull request by xuanxuanx-98**
…s and texts in footer bigger

### CODE REVIEW

**Review by akki2825 — CHANGES_REQUESTED** [review]
can you move the css in about_us.md to assets/css/

**Comment by xuanxuanx-98** [comment]
@akki2825 are you referring to:
# CSS class.
css_class = "custom-background"

I just found that this is a dummy .css class. There is no .css file called custom-background. If I remove it, the background is still correctly shown.

**Comment by akki2825** [comment]
please remove the css part in the markdown file

**Comment by xuanxuanx-98** [comment]
@akki2825 I applied changes on the existing PR. Does it work?

**Review by akki2825 — APPROVED** [review]

**Pull request merged**
